services:
  - type: web
    name: euro2020
    env: node
    plan: starter
    buildCommand:
      yarn --frozen-lockfile --prod=false &&
      blitz prisma generate &&
      blitz build &&
      blitz prisma migrate deploy
    startCommand: blitz start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: euro2020-db
          property: connectionString
      - key: SESSION_SECRET_KEY
        generateValue: true
      - key: APP_ORIGIN
        value: https://euro2020.onrender.com

databases:
  - name: euro2020-db
    plan: starter
